config/routes.rb
Hydra::Application.routes.draw do

  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/zotero', to: 'static_pages#zotero'
  get '/mendeley', to: 'static_pages#mendeley'

  root :to => "dams_units#index"
  resources :dams_collections, :only => [:show]
  get '/dlp', to: 'dams_units#show', :id => 'dlp'
  get '/rci', to: 'dams_units#show', :id => 'rci'
  get '/:id/collections', to: 'catalog#collection_search', :as => "dams_unit_collections"
  get "collections", :to => 'catalog#collection_search', :as => 'dams_collections'

  Blacklight.add_routes(self, :except => [:solr_document, :catalog]  )

  get 'search/opensearch', :as => "opensearch_catalog"
  get 'search/citation', :as => "citation_catalog"
  get 'search/email', :as => "email_catalog"
  get 'search/sms', :as => "sms_catalog"
  get 'search/endnote', :as => "endnote_catalog"
  get 'search/send_email_record', :as => "send_email_record_catalog"
  get "search/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  get "search", :to => 'catalog#index', :as => 'catalog_index'
  get 'search/:id/librarian_view', :to => "catalog#librarian_view", :as => "librarian_view_catalog"
  resources :solr_document, :path => 'search', :controller => 'catalog', :only => [:show, :update]
  resources :catalog, :only => [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    get '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end

  resources :dams_subjects, :only => [:show]

  resources :object, :controller => 'dams_objects', :as => 'dams_objects' do
    get 'view', :on => :member
  end

  post "object/:id/upload", :to => 'file#create', :as => 'upload'
  post "object/:id/deriv/:ds", :to => 'file#deriv', :as => 'deriv'
  get "object/:id/zoom/:cmp", :to => 'dams_objects#zoom', :as => 'zoom'
  get "object/:id/:ds", :to => 'file#show', :constraints => { :ds => /[^\/]+/ }, :as => 'file'
  resources :dams_assembled_collections do
    get 'view', :on => :member
  end
  resources :dams_units do
    member do
      get 'view'
      get 'collections'
    end
  end
  resources :dams_copyrights do
  	get 'view', :on => :member
  end
  resources :dams_licenses do
  	get 'view', :on => :member
  end
  resources :dams_other_rights do
  	get 'view', :on => :member
  end
  resources :dams_statutes do
  	get 'view', :on => :member
  end
  resources :dams_languages
  resources :dams_vocabularies
  resources :dams_roles
  resources :dams_provenance_collections
  resources :dams_provenance_collection_parts
  resources :dams_vocabulary_entries
  resources :dams_source_captures
  resources :dams_cartographics
  resources :dams_built_work_places do
    get 'view', :on => :member
  end
  resources :dams_foos do
    get 'view', :on => :member
  end
  resources :dams_foo_bars do
    get 'view', :on => :member
  end
  resources :dams_iconographies do
    get 'view', :on => :member
  end
  resources :dams_style_periods do
    get 'view', :on => :member
  end
  resources :dams_scientific_names do
    get 'view', :on => :member
  end
  resources :dams_techniques do
    get 'view', :on => :member
  end
  resources :dams_cultures do
    get 'view', :on => :member
  end
  resources :dams_cultural_contexts do
    get 'view', :on => :member
  end
  resources :dams_functions do
    get 'view', :on => :member
  end
  resources :mads_personal_names do
    get 'view', :on => :member
  end
  resources :mads_family_names do
    get 'view', :on => :member
  end
  resources :mads_corporate_names do
    get 'view', :on => :member
  end
  resources :mads_conference_names do
    get 'view', :on => :member
  end
  resources :mads_complex_subjects do
    get 'view', :on => :member
  end
  resources :mads_topics do
    get 'view', :on => :member
  end
  resources :mads_temporals do
    get 'view', :on => :member
  end
  resources :mads_names do
    get 'view', :on => :member
  end
  resources :mads_occupations do
    get 'view', :on => :member
  end
  resources :mads_genre_forms do
    get 'view', :on => :member
  end
  resources :mads_geographics do
    get 'view', :on => :member
  end
  resources :mads_schemes do
    get 'view', :on => :member
  end
  resources :mads_authority, :as => 'mads_authorities' do
    get 'view', :on => :member
  end
  resources :mads_languages do
    get 'view', :on => :member
  end

  resources :get_data do
	get 'get_linked_data', :on => :member
	post 'get_linked_data', :on => :member
	get 'get_name', :on => :member
	post 'get_name', :on => :member	
	get 'get_subject', :on => :member
	post 'get_subject', :on => :member
	get 'get_ark', :on => :member		
  end

end

app/helpers/dams_objects_helper.rb
require "base64"
require "openssl"

module DamsObjectsHelper

  #---
    # Openurl, embedded metadata support,
    # Get metadata from solr document, and parsing each field and produce openURL key-encoded value query strings.
    # create mapping from DAMS fields to dublin core fields
    # hweng@ucsd.edu
  #---
  def field_mapping(fieldName)
    data_arr=[]

    fieldData = getFieldData(fieldName)
     if fieldData != nil
      fieldData.each do |value|
        data_arr.push(value)
        end
     end
     data_arr
    end
  
 def getFieldData(fieldName)
       index = getComponentIndex
       fieldData = @document["#{index}#{fieldName}"]
 end

    def getComponentIndex
        index = (defined?(componentIndex)) ? "component_#{componentIndex}_" : ''
    end
    
    # Mapping from title_json_tesim, and concatenate as title_json_tesim.value:title_json_tesim.subTitle
    def getTitle
      data_arr=[]
      
      fieldData=getFieldData('title_json_tesim')
      title_value=''

       if fieldData != nil
         fieldData.each do |datum|
          title = JSON.parse(datum)
          if title['value'] != ''
             title_value=title['value']
             if title['subtitle'] != ''
              title_value=title_value+ title['subtitle']
             end
            data_arr.push(title_value)
          end
        end
       end 
        data_arr
    end


    #Need to update 
    def getCreator
      # data_arr=[]
      # get creator list from names:personal
       fieldValue=field_mapping('name_tesim')
      #if fieldValue != nil && fieldValue != ''
      #  data_arr.push(fieldValue)
      # end
       
      # get creator list from corporateName_tesim
      # fieldValue=field_mapping('corporateName_tesim')
      # if fieldValue != nil && fieldValue != ''
      #  data_arr.push(fieldValue)
      # end
    end

    def getFormat
       data_arr=[]
       fieldData=getFieldData('note_json_tesim')
       format_value=''
       concat__note_value=''
       concat__form_value=''
       concat__extent_value=''

       
       if fieldData != nil
         fieldData.each do |datum|
          format = JSON.parse(datum)
          if format['displayLabel'] == 'Form'
            concat__form_value=format['value']
          elsif format['displayLabel'] == 'Extent'
            concat__extent_value=format['value']
          elsif format['displayLabel'] == 'Note'
            concat__note_value=format['value']
          end
         end

         if concat__note_value!=''
           format_value=concat__note_value
         elsif concat__form_value!=''
            format_value=concat__form_value
            if concat__extent_value!=''
             format_value=format_value+";"+concat__extent_value
            end
         end
         data_arr.push(format_value)
       end 
        data_arr
    end


    def getDescription
       data_arr=[]
       fieldData=getFieldData('note_json_tesim')

       if fieldData != nil
         fieldData.each do |datum|
          note = JSON.parse(datum)
          if note['type'] == 'abstract'
            data_arr.push(note['value'])
          end
          end
        end 
        data_arr
    end
    
    def getRelation
       data_arr=[]
       fieldData=getFieldData('collection_json_tesim')
       
       # implementation for relation mapping
    end

    #Need refactor code when MADS implementation is done.
    def getCoverage
       data_arr=[]
       fieldData=getFieldData('cartographics_json_tesim')
       coverage_value=''
       
       if fieldData != nil
         fieldData.each do |datum|
          coverage = JSON.parse(datum)
          if coverage['scale'] != ''
            coverage_value=coverage['scale']
            if coverage['projection'] != ''
              coverage_value=coverage_value+coverage['projection']
              if coverage['coordinates'] != ''
                coverage_value=coverage_value+coverage['coordinates']
              end
            end

            data_arr.push(coverage_value)
          end
         end
        end 
        data_arr
    end

    #Need refactor code when MADS implementation is done.
    def getSubject

       fieldValue=field_mapping('subject_tesim')
    end

    

    def getDate
       data_arr=[]
       index = getComponentIndex
       fieldData = @document["#{index}date_json_tesim"]
       
       if fieldData != nil
         fieldData.each do |datum|
          date = JSON.parse(datum)
          if date['value'] != ''
            data_arr.push(date['value'])
          end
          end
        end 
        data_arr
    end
    

    
    def getLanguage
        fieldValue=field_mapping('language_tesim')
    end

    def getIdentifier
       data_arr=[]
       index = getComponentIndex
     fieldData = @document["#{index}note_json_tesim"]

     if fieldData != nil
       fieldData.each do |datum|
          note = JSON.parse(datum)
          if note['displayLabel'] == 'ARK'
            data_arr.push(note['value'])
          end
       end
      end
     data_arr
    end

   #dc:publisher
   def getPublisher
       data_arr=[]
       fieldData=getFieldData('note_json_tesim')

       if fieldData != nil
         fieldData.each do |datum|
          note = JSON.parse(datum)
          if note['type'] == 'publication'
            data_arr.push(note['value'])
          end
          end
        end 
        data_arr
    end
    
    def getCopyright
       data_arr=[]
       index = getComponentIndex
     fieldData = @document["#{index}copyright_tesim"]
     if fieldData != nil
      fieldJSON = JSON.parse(fieldData.first)
        temp =fieldJSON['purposeNote']
        temp ='purposeNote: '+temp + ' '+'note: '+fieldJSON['note']
        data_arr.push(temp)
     end
     data_arr
    end
   
   def export_as_openurl
        query_string = []
        query_string << "url_ver=Z39.88-2004&ctx_ver=Z39.88-2004&rft_val_fmt=info%3Aofi%2Ffmt%3Akev%3Amtx%3Adc&rfr_id=info%3Asid%2Fblacklight.rubyforge.org%3Agenerator"
        field_map = {
          'title' => getTitle,
          'creator'=>getCreator,
          'subject'=>getSubject,
          'description'=>getDescription,
          'date'=>getDate,
          'format'=>getFormat,
          'language'=> getLanguage,
          'identifier'=>getIdentifier,
          #'coverage'=>getCoverage,
           'publisher'=>getPublisher,
           'rights'=> getCopyright
          
        }
        field_map.each do |kev, values|
          next if values.empty? or values.first.nil?
          values.each do |value|
            query_string << "rft.#{kev}=#{CGI::escape(value)}"
          end
        end
        query_string.join('&') unless query_string.blank?
    end

  #--
  # End of openURL implementation
  #    


  #---
  # select_file: Select files to display
  #---
  def select_file( params )
    document  = params[:document]
    component = params[:component]
    max_size  = params[:quality]
    type      = params[:type]
  
    prefix = (component != nil) ? "component_#{component}_" : ""
    files = document["#{prefix}files_tesim"]

    # identify acceptable files
    service_use = nil
    service_dim = 0
    service_json = nil
    display_dim  = 0
    display_json = nil
    if files != nil
      files.each{ |f|
        fjson = JSON.parse(f)
        fid = fjson["id"]
        use = fjson["use"]
        if use != nil
          use = use.first
        end
        qual = fjson["quality"]
        if qual != nil
          qualArr = qual.split("x")
          file_dim = qualArr.max { |a,b| a.to_i <=> b.to_i }.to_i
        end
        if type == nil || use.start_with?(type)
          if use != nil && use.end_with?("-service")
            if (service_json == nil || service_use.start_with?("image-") )
              service_json = fjson
              service_use = use
              service_dim = file_dim.to_i
            end
          elsif max_size == nil || file_dim == nil || file_dim.to_i < max_size
            if (display_json == nil || file_dim.to_i > display_dim) && use != nil && (not use.end_with?("-source") )
              display_json = fjson
              display_dim  = file_dim.to_i
            end
          end
        end
      }
    end
  
    # build file metadata hash
    info = Hash.new
    if ( service_json != nil )
      info[:service] = service_json
    end
    if ( display_json != nil )
      info[:display] = display_json
    end
    info
  end

  #---
  # render_file_use
  #---
  def render_file_use( params )
    component = params[:component]
		quality = params[:quality]

    if component=="0"
      files = select_file( :document=>@document, :quality=>quality )
    else
      files = select_file( :document=>@document, :component=>component, :quality=>quality )
    end
   
    file_info = files[:service]
    if file_info != nil
      use = file_info['use'].first
    end
  end

  #---
  # render_service_file
  #---
  def render_service_file( params )
    component = params[:component]
		quality = params[:quality]

    if component=="0"
      files = select_file( :document=>@document, :quality=>quality )
    else
      files = select_file( :document=>@document, :component=>component, :quality=>quality )
    end

    service_file = files[:service]
    if service_file != nil
      services=service_file["id"]
    end
  end

  #---
  # render_display_file
  #---
  def render_display_file( params )
    component = params[:component]
		quality = params[:quality]

    if component=="0"
      files = select_file( :document=>@document,:quality=>quality )
    else
      files = select_file( :document=>@document, :component=>component, :quality=>quality )
    end

    if files.has_key?(:display)
      display_file = files[:display]
      display=display_file["id"]
    else
      service_file = files[:service]
      if service_file != nil
        services=service_file["id"]
      
        #---
        # todo: replace no_display with appreciate icons"
        #--
        if services.include?('mp3')

app/views/dams_objects/_audio_viewer.html.erb
<%
   prefix = (defined?(componentIndex)) ? "component_#{componentIndex}_" : ''
   objid = @document['id']
   cmpid = (defined?(componentIndex)) ? "#{componentIndex}" : '0'
   fieldData = @document["#{prefix}files_tesim"]
   wowzaURL = grabWowzaURL(fieldData,objid,cmpid)
%>

<% if wowzaURL != nil %>

  <div id="dams-audio">Loading the player...</div>

  <script type="text/javascript">
	  jwplayer("dams-audio").setup({
		  playlist:
				  [{
					  sources:
							  [
								  {file: "rtmp://<%=wowzaURL%>"},
								  {file: "http://<%=wowzaURL%>/playlist.m3u8"}
							  ]
				  }],
		  width: "100%",
		  height: 25,
		  controlBar:'bottom',
		  rtmp: {bufferlength: 3},
		  analytics: {enabled: false},
		  primary: "flash",
		  fallback: false
	  });
  </script>

<% end %>

app/views/dams_objects/_audio_viewer_complex.html.erb
<%
   prefix = (defined?(componentIndex)) ? "component_#{componentIndex}_" : ''
   objid = @document['id']
   cmpid = (defined?(componentIndex)) ? "#{componentIndex}" : '0'
   fieldData = @document["#{prefix}files_tesim"]
   wowzaURL = grabWowzaURL(fieldData,objid,cmpid)
   dataForDynamicLoad = "{\"file_type\":\"audio\",\"display_file_path\":\"\",\"service_file_path\":\"#{wowzaURL}\"}"
%>

<% if wowzaURL != nil %>

  <div id="dams-audio-<%=componentIndex%>" data='<%=dataForDynamicLoad%>'>Loading the player...</div>

<% end %>

app/views/dams_objects/_default_viewer.html.erb
<div class="form-actions dams-download-button">
	<%# <p class="muted"> %>
		<%# <small> %>
			<%# if objectType == 'simple' %>
				<%# There are no files associated with this object. %>
			<%# elsif objectType == 'complex' %>
				<%# There are no files associated with this component. %>
			<%# else %>
				<%# There are no files associated with this object or component. %>
			<%# end %>
		<%# </small> %>
	<%# </p> %>
</div>

app/views/dams_objects/_init.html.erb
<script>
	if (document.getElementById("simple-audio")){
		audiojs.events.ready(function(){audiojs.create(document.getElementById("simple-audio"));});
	}
</script>

app/views/dams_objects/_metadata_component.html.erb
<% if defined?(componentIndex) %>

	<table class="table">
		<tbody>

			<% if defined?(fileName) # Our component has files associated with it. %>

				<%= render :partial => 'shared/fields/date', :locals => {:componentIndex => componentIndex} %>
				<%= render :partial => 'shared/fields/note', :locals => {:componentIndex => componentIndex} %>

				<% if defined?(fileMetadata) %>
					<% if fileMetadata == true %>
						<%= render :partial => 'shared/fields/file_size', :locals => {:componentIndex => componentIndex, :fileName => fileName} %>
						<%= render :partial => 'shared/fields/file_format', :locals => {:componentIndex => componentIndex, :fileName => fileName} %>
					<% end %>
				<% end %>

			<% else # Our component doesn't have any files associated with it. The poor thing. %>

				<%= render :partial => 'shared/fields/resource_type', :locals => {:componentIndex => componentIndex} %>
				<%= render :partial => 'shared/fields/topic', :locals => {:componentIndex => componentIndex} %>
				<%= render :partial => 'shared/fields/note', :locals => {:componentIndex => componentIndex} %>

			<% end %>

		</tbody>
	</table>

<% end %>

app/views/dams_objects/_object_viewer.html.erb
<div class="row-fluid">
	<section class="span12">
		<% if @document['id'] != nil %>
			<% if @document['component_count_isi'] != nil %>

				<%# THE COMPLEX OBJECT SAYS, "IPSA SCIENTIA POTESTAS EST" %>
				<%= render :partial => 'complex_object_viewer' %>

			<% else %>

				<%# THE SIMPLE OBJECT SEZ, "DERP" %>
				<%
					ark = render_document_show_field_value(:document=>@document, :field=>'id')

					fileType = grabFileUse()
					display_file = grabDisplayFile()
					service_file = grabServiceFile()
					display_file_path = (display_file != 'no_display') ? file_path(ark,"_#{display_file}") : ''
					service_file_path = (service_file != nil) ? file_path(ark,"_#{service_file}") : ''
					zoom_file_path = zoom_path @document['id'], '0'
				%>

				<%= render :partial => 'simple_object_viewer',
				           :locals => {
						           :fileType => fileType,
						           :display_file_path => display_file_path,
						           :service_file_path => service_file_path,
						           :service_file => service_file,
						           :zoom_file_path => zoom_file_path
				           }
				%>

			<% end %>
		<% end %>
	</section>
</div>

app/views/dams_objects/_pdf_viewer.html.erb
	<div class="well dams-download-button">
		<a class="btn btn-large btn-block btn-primary" href="<%= source %>" target="_blank">
			<i class="icon-download-alt icon-white"></i>
			Download PDF
		</a>
	</div>


app/views/dams_objects/_prev_next.html.erb
<% if @previous_document || @next_document %>
  <div class="search-results-pager">
    <%#= render_constraints(session[:search]) %>
    <%
      curr = session[:search][:counter].to_i
      total = session[:search][:total].to_i
      prev_item = curr - 1
      next_item = curr + 1

	    users_search_term = session[:search][:q]
	    bonus_text = "<span>for <abbr title='#{users_search_term}'>%s</abbr></span>"

	    if users_search_term != nil
		    users_search_term = (users_search_term.length > 16) ? "#{users_search_term[0...15]}..." : users_search_term
				bonus_text %= users_search_term
			else
			  bonus_text = ''
	    end
     %>
    <% if prev_item > 0 %>
      <%= link_to_document @previous_document, :label => '<i class="icon-backward"></i> <span>Previous</span>'.html_safe, :counter => prev_item, :force_label => true %>
    <% end %>
    <span><%= item_page_entry_info %> results <%= bonus_text.html_safe %></span>
    <% if next_item <= total %>
      <%= link_to_document @next_document, :label => '<span>Next</span> <i class="icon-forward"></i>'.html_safe, :counter => next_item, :force_label => true %>
    <% end %>
  </div>
<% end %>

app/views/dams_objects/_show_damstools.html.erb
<!--<p>Export to: -->

<%#= link_to 'Zotero', zotero_path, {:id => 'zoteroLink', :name => 'zotero', :class => 'btn btn-mini btn-primary'} %>
      
<%#= link_to 'Mendeley', mendeley_path, {:id => 'mendeleyLink', :name => 'mendeley', :class => 'btn btn-mini btn-primary'} %>


 <!-- COinS hook for openurl -->
    <span class="Z3988" title="<%= export_as_openurl %>"></span>

app/views/dams_objects/_video_viewer_complex.html.erb
<%
   prefix = (defined?(componentIndex)) ? "component_#{componentIndex}_" : ''
   objid = @document['id']
   cmpid = (defined?(componentIndex)) ? "#{componentIndex}" : '0'
   fieldData = @document["#{prefix}files_tesim"]
   wowzaURL = grabWowzaURL(fieldData,objid,cmpid)
   dataForDynamicLoad = "{\"file_type\":\"video\",\"display_file_path\":\"\",\"service_file_path\":\"#{wowzaURL}\"}"
%>

<% if wowzaURL != nil %>

  <div id="dams-video-<%=componentIndex%>" data='<%=dataForDynamicLoad%>'>Loading the player...</div>

<% end %>

app/views/dams_objects/new.html.erb
<%= javascript_tag "var baseURL = '#{url_for( :controller => 'get_data', :only_path => false )}';" %>
<h1>Create a new Dams Object</h1>
<div class="dams-viewer">
<%= form_for @dams_object , :html => { :onsubmit => 'processForm_generic("#dams_object_");', :multipart => true, :id => 'fileupload', :method => 'post'} do |f| %>

  <%= render :partial => 'shared/edit_fields/title_form' , :locals => {:f => f}%>

  <%= render :partial => 'shared/edit_fields/type_of_resource_form', :locals => {:f => f, :object => @dams_object, :object_type => "dams_object"}%>

  <%= render :partial => 'shared/edit_fields/date_form' , :locals => {:f => f, :object_type => "dams_object"}%>
         
  <%= render :partial => 'shared/edit_fields/unit_form' , :locals => {:f => f, :object_type => "dams_object"}%>
     
  <%= render :partial => 'shared/edit_fields/collections_form', :locals => {:f => f, :object_type => "dams_object"}%>

  <%= render :partial => 'shared/edit_fields/language_form' , :locals => {:f => f, :object_type => "dams_object", :is_first => "true"}%>
      
  <%= render :partial => 'shared/edit_fields/notes_form' , :locals => {:f => f, :object_type => "dams_object"}%>
        
  <%= render :partial => 'shared/edit_fields/relationship_form' , :locals => {:f => f, :object_type => "dams_object"}%>
  
  <%= render :partial => 'shared/edit_fields/complex_subjects_form' , :locals => {:f => f, :object_type => "dams_object"}%> 
       
  <%= render :partial => 'shared/edit_fields/simple_subjects_form' , :locals => {:f => f, :object_type => "dams_object"}%>
    
  <%= render :partial => 'shared/edit_fields/creator_form' , :locals => {:f => f, :object_type => "dams_object"}%>
        
  <%= render :partial => 'shared/edit_fields/rights_form' , :locals => {:f => f, :object_type => "dams_object"}%>
    
  <%= render :partial => 'shared/edit_fields/related_resource_form' , :locals => {:f => f, :object_type => "dams_object"}%>

  <%= render :partial => 'shared/edit_fields/cartographics_form' , :locals => {:f => f, :object_type => "dams_object"}%>  

  <h3>Add File</h3>
  <input type="file" name="file"/>

  <!--input type="text" id="test" data-provide="typeahead" data-items="3" data-source='<%= @autocomplete_items %>'-->
  <br/><br/>

  <%=f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", dams_objects_path, class: "btn btn-primary" %>   
<%end%>
</div>

app/views/dams_objects/show.html.erb
<%
	@page_title =  "#{grabTitle}"
%>

<% @ds = flash[:deriv] %>
<%# if @ds != nil %>
  <%#= button_to( "Generate Derivatives", deriv_path( @document['id'], @ds ), remote: true, data: {disable_with: 'Generating...'}, form: {id: "generate_derivatives"}, class: 'btn' ) %>
<%# end %>

<div class="row-fluid">
  <div class="span12">
    <%= render :partial => 'prev_next' %>
  </div>
</div>

<div class="row-fluid">
  <div id="content" class="show-document span9">

    <div class="row-fluid">
			<section class="dams-viewer span12">
			  <%= render :partial => 'shared/fields/title' %>
				<%= render :partial => 'object_viewer' %>
			</section>
		</div>

		<div class="row-fluid">
			<section class="dams-metadata span12">
				<%= render :partial => 'shared/fields/show' %>
			</section>
		</div>

	 </div>
	 <div class="span3">

		<div class="row-fluid">
			<section class="dams-sidebar span12">
				<%if @document['component_count_isi'] != nil   %>
					<%= render :partial => 'component_tree' %>
				<% end %>
				<%= render :partial => 'related_resources' %>
			</section>
		</div>

		<% if can? :update, @document then %>
		  <div class="row-fluid">
		    <p class="sidebar-header"><strong>Editor Tools</strong></p>
		    <ul class="unstyled sidebar-button-list">
		      <li><%= link_to "<i class='icon-plus-sign'></i> Hydra View".html_safe, view_dams_object_path(@document['id']), class: "btn btn-block btn-small btn-link"%>
		      <li><%= link_to "<i class='icon-plus-sign'></i> RDF View".html_safe, normalized_rdf_path(@document['id']), class: "btn btn-block btn-small btn-link"%>
		      <li><%= link_to "<i class='icon-plus-sign'></i> Edit".html_safe, edit_dams_object_path(@document['id']), class: "btn btn-block btn-small btn-link"%>
		    </ul>
		  </div>
		<% end %>

		<%= render :partial => 'show_damstools' %>

	</div>
</div>

<div class="row-fluid">
	<section class="dams-comments span9">
		<%= render :partial => 'comments' %>
	</section>
</div>



app/views/dams_objects/zoom.html.erb
<%
  @page_title =  "Object | #{grabTitle}"
  @cmp = params['cmp']
  files_key = (@cmp != '0') ? "component_#{@cmp}_files_tesim" : "files_tesim"
  @files = @document[files_key] || []
  @files.each do |f|
    json = JSON.parse(f)
    use = json['use']
    @file_id = json['id']
    #image-source and image-service master files
    if use == 'image-source' || use == 'document-service' || (!json['id'].blank? && json['id'].start_with?("1.") && use == 'image-service')
      @quality = json['quality']
      #When quality property not presented,set to image-huge for now?
      if @quality.blank?
        @quality = "1600x1600"
      end
      break
    end
  end
  if @quality.blank? %>
  <p>Error: unable to find zoomable image.</p>
<%
  else
    dim = @quality.split("x")
    p1 = @object[0,2]
    p2 = @object[2,2]
    dir = p1 + "/" + p2 + "/" + @object
    dir += "-#{@cmp}" if @cmp != '0'
%>
  <style type="text/css">
    html, body, #map {
      width: 100%; height: 100%; padding: 0; margin: 0;
    }
  </style>
  <div id="map"></div>
  <script type="text/javascript">
    var map = L.map('map').setView(new L.LatLng(0,0), 0);
    L.tileLayer.zoomify('<%=Rails.configuration.zoomify_baseurl%><%=dir%>/', { 
      width: <%=dim[0]%>, height: <%=dim[1]%>
    }).addTo(map);
  </script>
<% end %>