config/routes.rb
Hydra::Application.routes.draw do

  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/zotero', to: 'static_pages#zotero'
  get '/mendeley', to: 'static_pages#mendeley'

  root :to => "dams_units#index"
  resources :dams_collections, :only => [:show]
  get '/dlp', to: 'dams_units#show', :id => 'dlp'
  get '/rci', to: 'dams_units#show', :id => 'rci'
  get '/:id/collections', to: 'catalog#collection_search', :as => "dams_unit_collections"
  get "collections", :to => 'catalog#collection_search', :as => 'dams_collections'

  Blacklight.add_routes(self, :except => [:solr_document, :catalog]  )

  get 'search/opensearch', :as => "opensearch_catalog"
  get 'search/citation', :as => "citation_catalog"
  get 'search/email', :as => "email_catalog"
  get 'search/sms', :as => "sms_catalog"
  get 'search/endnote', :as => "endnote_catalog"
  get 'search/send_email_record', :as => "send_email_record_catalog"
  get "search/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  get "search", :to => 'catalog#index', :as => 'catalog_index'
  get 'search/:id/librarian_view', :to => "catalog#librarian_view", :as => "librarian_view_catalog"
  resources :solr_document, :path => 'search', :controller => 'catalog', :only => [:show, :update]
  resources :catalog, :only => [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    get '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end

  resources :dams_subjects, :only => [:show]

  resources :object, :controller => 'dams_objects', :as => 'dams_objects' do
    get 'view', :on => :member
  end

  post "object/:id/upload", :to => 'file#create', :as => 'upload'
  post "object/:id/deriv/:ds", :to => 'file#deriv', :as => 'deriv'
  get "object/:id/zoom/:cmp", :to => 'dams_objects#zoom', :as => 'zoom'
  get "object/:id/:ds", :to => 'file#show', :constraints => { :ds => /[^\/]+/ }, :as => 'file'
  resources :dams_assembled_collections do
    get 'view', :on => :member
  end
  resources :dams_units do
    member do
      get 'view'
      get 'collections'
    end
  end
  resources :dams_copyrights do
  	get 'view', :on => :member
  end
  resources :dams_licenses do
  	get 'view', :on => :member
  end
  resources :dams_other_rights do
  	get 'view', :on => :member
  end
  resources :dams_statutes do
  	get 'view', :on => :member
  end
  resources :dams_languages
  resources :dams_vocabularies
  resources :dams_roles
  resources :dams_provenance_collections
  resources :dams_provenance_collection_parts
  resources :dams_vocabulary_entries
  resources :dams_source_captures
  resources :dams_cartographics
  resources :dams_built_work_places do
    get 'view', :on => :member
  end
  resources :dams_foos do
    get 'view', :on => :member
  end
  resources :dams_foo_bars do
    get 'view', :on => :member
  end
  resources :dams_iconographies do
    get 'view', :on => :member
  end
  resources :dams_style_periods do
    get 'view', :on => :member
  end
  resources :dams_scientific_names do
    get 'view', :on => :member
  end
  resources :dams_techniques do
    get 'view', :on => :member
  end
  resources :dams_cultures do
    get 'view', :on => :member
  end
  resources :dams_cultural_contexts do
    get 'view', :on => :member
  end
  resources :dams_functions do
    get 'view', :on => :member
  end
  resources :mads_personal_names do
    get 'view', :on => :member
  end
  resources :mads_family_names do
    get 'view', :on => :member
  end
  resources :mads_corporate_names do
    get 'view', :on => :member
  end
  resources :mads_conference_names do
    get 'view', :on => :member
  end
  resources :mads_complex_subjects do
    get 'view', :on => :member
  end
  resources :mads_topics do
    get 'view', :on => :member
  end
  resources :mads_temporals do
    get 'view', :on => :member
  end
  resources :mads_names do
    get 'view', :on => :member
  end
  resources :mads_occupations do
    get 'view', :on => :member
  end
  resources :mads_genre_forms do
    get 'view', :on => :member
  end
  resources :mads_geographics do
    get 'view', :on => :member
  end
  resources :mads_schemes do
    get 'view', :on => :member
  end
  resources :mads_authority, :as => 'mads_authorities' do
    get 'view', :on => :member
  end
  resources :mads_languages do
    get 'view', :on => :member
  end

  resources :get_data do
	get 'get_linked_data', :on => :member
	post 'get_linked_data', :on => :member
	get 'get_name', :on => :member
	post 'get_name', :on => :member	
	get 'get_subject', :on => :member
	post 'get_subject', :on => :member
	get 'get_ark', :on => :member		
  end

end

app/models/mads_occupation.rb
class MadsOccupation < ActiveFedora::Base
  has_metadata 'damsMetadata', :type => MadsOccupationDatastream 
  delegate_to "damsMetadata", [:name, :scheme, :elementList, :externalAuthority, :occupationElement_attributes, :occupationElement, :scheme_attributes]
  
end

app/controllers/mads_occupations_controller.rb
class MadsOccupationsController < ApplicationController
  include Blacklight::Catalog
  include Dams::ControllerHelper
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:index, :show]

  ##############################################################################
  # solr actions ###############################################################
  ##############################################################################
  def show
    parm={ :q => "id_t:#{params[:id]}" }
    @document = get_single_doc_via_search(1,parm)
    @current_occupation = @document['name_tesim']
    #@carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel AND id_t:#{params[:id]}", :qt=>"standard")
     @carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel")
  end
  def index
    # hydra index
    #@mads_occupations = MadOccupation.all( :order=>"system_create_dtsi asc" )

    # solr index
    @response, @document = get_search_results(:q => 'has_model_ssim:"info:fedora/afmodel:MadsOccupation"' )
    @carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel")
  end

  ##############################################################################
  # hydra actions ##############################################################
  ##############################################################################
  def view
    @mads_occupation = MadsOccupation.find(params[:id])
  end

  def new
    @mads_occupation.elementList.occupationElement.build
    @mads_occupation.scheme.build
	@mads_schemes = get_objects('MadsScheme','name_tesim')
    #@mads_schemes = MadsScheme.all( :order=>"system_create_dtsi asc" )
  end

  def edit
    @mads_schemes = get_objects('MadsScheme','name_tesim')
    #@mads_schemes = MadsScheme.all( :order=>"system_create_dtsi asc" )
    @scheme_id = Rails.configuration.id_namespace+@mads_occupation.scheme.to_s.gsub(/.*\//,'')[0..9]
  end

  def create
    if @mads_occupation.save
	    if(!params[:parent_id].nil?)
			redirect_to view_mads_occupation_path(@mads_occupation, {:parent_id => params[:parent_id]})
	    elsif(!params[:parent_class].nil?)
			redirect_to view_mads_occupation_path(@mads_occupation, {:parent_class => params[:parent_class]}) 	    			 	    
	    else  
        	redirect_to @mads_occupation, notice: "Occupation has been saved"
        end
    else
      flash[:alert] = "Unable to save Occupation"
      render :new
    end
  end

  def update
    @mads_occupation.elementList.clear
    @mads_occupation.scheme.clear
    @mads_occupation.attributes = params[:mads_occupation]
    if @mads_occupation.save
    	if(!params[:parent_id].nil? && params[:parent_id].to_s != "")
        	redirect_to edit_mads_complex_subject_path(params[:parent_id]), notice: "Successfully updated Occupation"
        else  
        	redirect_to @mads_occupation, notice: "Successfully updated Occupation"
        end
    else
      flash[:alert] = "Unable to save occupation"
      render :edit
    end
  end

end

app/views/mads_occupations/_error_messages.html.erb
<% if @mads_occupation.errors.any? %>

	<div class="alert alert-block alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<h4>The form contains <%= pluralize(@mads_occupation.errors.count, "error") %></h4>
		<ul>
		<% @mads_occupation.errors.full_messages.each do |msg| %>
			<li><%= msg %></li> 
		<% end %>
		</ul>
	</div>

<% end %>

app/views/mads_occupations/_occupation_links.html.erb
<li><%= link_to mads_occupation['name_tesim'], mads_occupation %></li>

app/views/mads_occupations/edit.html.erb
<% @page_title =  "Edit Occupation" %>

<div class="row-fluid">
	<div class="span10 offset1">
	
		<h2>Edit Occupation</h2>
		
		<%= form_for @mads_occupation do |f| %>
		
			<%= render 'error_messages', object: f.object %>
		
			<%= label_tag 'mads_occupation[name][]', "Name" %>
			<%= text_field_tag 'mads_occupation[name][]', @mads_occupation.name[0], class: "input-block-level" %>
		
			<%= label_tag 'mads_occupation[externalAuthority][]', "ExternalAuthority" %>
			<%= text_field_tag 'mads_occupation[externalAuthority][]', @mads_occupation.externalAuthority, class: "input-block-level" %>

		      <%= f.fields_for :scheme, include_id: false do |se| %>
		        <%= se.label :id, "Scheme" %>
		        <%= se.select :id, options_for_select(@mads_schemes, :selected => @scheme_id) , :prompt=>"Select MadsScheme" %>
		      <% end %>
		      <%= f.fields_for :occupationElement do |te| %>
		        <%= te.label :elementValue, "Element Value" %>
		        <%= te.text_field :elementValue, class: "input-block-level" %>
		      <% end %>
				
			<div class="form-actions">
				<button type="submit" class="btn btn-primary pull-right">Save changes</button>
				<%= link_to "Cancel", mads_occupation_path(@mads_occupation), class: "btn btn-link pull-right" %>
			</div>
				
		
		<%end%>
	
	</div>
</div>

app/views/mads_occupations/index.html.erb
<div class="row-fluid">
	<div class="span12">
		<h1>Digital Collections</h1>
	</div>
</div>

<div class="row-fluid">

    <div id="myCarousel" class="carousel slide span8">
    <div class="carousel-inner">

			
			<div class="item">
				<%= image_tag file_path 'bd95572101', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: Scripps Institution of Oceanography Geological Collections</p>
				</div>
			</div>
			
			<div class="item">
				<%= image_tag file_path 'bd21510035', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: The UCSD Levantine Archaeology Laboratory</p>
				</div>
			</div>

			<div class="item">
				<%= image_tag file_path 'bd5666392f', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: UCSD History</p>
				</div>
			</div>
			
			<div class="item">
				<%= image_tag file_path 'bd82602702', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: The Laboratory for Computational Astrophysics</p>
				</div>
			</div>
			
			<div class="item">
					<%= image_tag file_path 'bd3413814d', '_2.jpg' %>
					<div class="carousel-caption">
						<p>Collection: The Brain Observatory</p>
					</div>
				</div>

			<div class="item">
				<%= image_tag file_path 'bd4369453c', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: Latin American Political Campaign Ephemera Collection</p>
				</div>
			</div>

			<div class="item">
				<%= image_tag file_path 'bd3106642r', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Baja California Collection</p>
				</div>
			</div>

			<div class="item">
				<%= image_tag file_path 'bd18097029', '_2.jpg' %>
				<div class="carousel-caption">
					<p>Collection: Tuzin Archive for Melanesian Anthropology</p>
				</div>
			</div>
	
				<div class="item">
					<%= image_tag file_path 'bd08540633', '_2.jpg' %>
					<div class="carousel-caption">
						<p>Collection: The National Science Foundation OpenTopography Facility</p>
					</div>
				</div>
	
				<div class="active item">
					<%= image_tag file_path 'bd6963330m', '_2.jpg' %>
					<div class="carousel-caption">
						<p>Collection: Scripps Institution of Oceanography Archives</p>
					</div>
				</div>
	
				

    </div>

    <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
    <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
    </div>
		
		
	
	<div class="span4">
	
		<div class="well dams-search-box">
			<p>Search</p>
			<%= render_unit_search_bar  %>
		</div>
			
		<p class="sidebar-header"><strong>Occupation</strong></p>
		<% @document.each do |doc| %>
			<% if doc['name_tesim'] != nil %>
				<%= link_to doc['name_tesim'].first, mads_occupation_path(doc['id_t']), :class => "btn btn-block" %>
			<% end %>
		<% end %>

		<p class="sidebar-header"><strong>Browse By </strong></p>
		<ul class="unstyled sidebar-button-list">
			<%= render_browse_facet_links %>
		</ul>
		
		<% if can? :create, DamsObject %>
			<p class="sidebar-header"><strong>Editor Tools</strong></p>
			<ul class="unstyled sidebar-button-list">
			<li><%= link_to "<i class='icon-plus-sign'></i> Create Occupation".html_safe, new_mads_occupation_path, :class => "btn btn-block btn-small btn-link" %>
			<li><%= link_to "<i class='icon-plus-sign'></i> Create Object".html_safe, new_dams_object_path, :class => "btn btn-block btn-small btn-link" %>
			</ul>
		<% end %>
	
	</div>

</div>

app/views/mads_occupations/new.html.erb
<h1>Create a new MADS Occupation</h1>
<%= form_for @mads_occupation do |f| %>
	<%= render 'error_messages' %>
  <%= label_tag 'mads_occupation[name]', "Name" %>
  <%= text_field_tag 'mads_occupation[name]', '', required: true %>
  <%= label_tag 'mads_occupation[externalAuthority]', "ExternalAuthority" %>
  <%= url_field_tag 'mads_occupation[externalAuthority]' %> 
   <%= f.fields_for :occupationElement do |te| %>
    <%= te.label :elementValue, "Element Value" %>
    <%= te.text_field :elementValue %>
  <% end %>
  <br>
  <%= render :partial => 'shared/edit_fields/scheme_fields' , :locals => {:f => f}%>
  <br>

  <%= render :partial => 'shared/edit_fields/new_form_hidden_fields' , :locals => {:parent_id => params[:parent_id], :parent_class => params[:parent_class]}%>

  <%=f.submit "Submit", class: "btn btn-primary" %>
<%end%>

app/views/mads_occupations/show.html.erb
<% @page_title =  "Occupation | #{render_document_show_field_value(:document=>@document, :field=>"name_tesim")} " %>
<% occupation = render_document_show_field_value(:document=>@document, :field=>"name_tesim") %>

<div class="row-fluid">

  <div id="content" class="show-document span9">

		<div class="row-fluid">
			<section class="dams-metadata span12">
				<p class="sidebar-header"><strong><%= occupation %></strong></p>			
				<dl class="dl-horizontal">
					<%= render :partial => 'shared/fields/metadata' %>
				</dl>	
			</section>
		</div>

	 </div>    
	
	<div class="span3">
	
		<div class="well dams-search-box">
			<h4>Search</h4>
			<%= render_unit_search_bar  %>
		</div>
		
		<p class="sidebar-header"><strong>Browse By</strong></p>
		<ul class="unstyled sidebar-button-list">
			<!-- hack in browse by collection, for RCI demo -->
			<li><%= link_to "<i class='icon-eye-open'></i> Collection".html_safe, dams_collections_path, :class => "btn btn-block  btn-link" %></li>
			<%= render_browse_facet_links %>
		</ul>

    <% if can? :update, @document then %>
			<p class="sidebar-header"><strong>Editor Tools</strong></p>
			<ul class="unstyled sidebar-button-list">
			<li><%= link_to "<i class='icon-plus-sign'></i> Hydra View".html_safe, view_mads_occupation_path(@document['id']), class: "btn btn-block btn-small btn-link"%>     
      		<li><%= link_to "<i class='icon-plus-sign'></i> Edit".html_safe, edit_mads_occupation_path(@document['id']), class: "btn btn-block btn-small btn-link"%>
			</ul>
    <% end %>
				
	</div>

</div>

app/views/mads_occupations/view.html.erb
<h1><%= @mads_occupation.name.first %></h1>

<div>
  <dl>
    <dt>OccupationElement:</dt>
    <dd><%= @mads_occupation.elementList[0].elementValue %></dd>
    <dt>Scheme:</dt>
    <dd><%= @mads_occupation.scheme.first.pid %></dd>
    <dt>ExternalAuthority:</dt>
    <dd><%= @mads_occupation.externalAuthority.first %></dd>
  </dl>
  <%= render :partial => 'shared/edit_fields/view_form_hidden_fields' , :locals => {:object => @mads_occupation, :parent_id => params[:parent_id], :parent_class => params[:parent_class]}%>
</div>