config/routes.rb
Hydra::Application.routes.draw do

  get '/faq', to: 'static_pages#faq'
  get '/about', to: 'static_pages#about'
  get '/zotero', to: 'static_pages#zotero'
  get '/mendeley', to: 'static_pages#mendeley'

  root :to => "dams_units#index"
  resources :dams_collections, :only => [:show]
  get '/dlp', to: 'dams_units#show', :id => 'dlp'
  get '/rci', to: 'dams_units#show', :id => 'rci'
  get '/:id/collections', to: 'catalog#collection_search', :as => "dams_unit_collections"
  get "collections", :to => 'catalog#collection_search', :as => 'dams_collections'

  Blacklight.add_routes(self, :except => [:solr_document, :catalog]  )

  get 'search/opensearch', :as => "opensearch_catalog"
  get 'search/citation', :as => "citation_catalog"
  get 'search/email', :as => "email_catalog"
  get 'search/sms', :as => "sms_catalog"
  get 'search/endnote', :as => "endnote_catalog"
  get 'search/send_email_record', :as => "send_email_record_catalog"
  get "search/facet/:id", :to => 'catalog#facet', :as => 'catalog_facet'
  get "search", :to => 'catalog#index', :as => 'catalog_index'
  get 'search/:id/librarian_view', :to => "catalog#librarian_view", :as => "librarian_view_catalog"
  resources :solr_document, :path => 'search', :controller => 'catalog', :only => [:show, :update]
  resources :catalog, :only => [:show, :update]

  HydraHead.add_routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  devise_scope :user do
    get '/users/sign_in', :to => "users/sessions#new", :as => :new_user_session
    get '/users/sign_out', :to => "users/sessions#destroy", :as => :destroy_user_session
  end

  resources :dams_subjects, :only => [:show]

  resources :object, :controller => 'dams_objects', :as => 'dams_objects' do
    get 'view', :on => :member
  end

  post "object/:id/upload", :to => 'file#create', :as => 'upload'
  post "object/:id/deriv/:ds", :to => 'file#deriv', :as => 'deriv'
  get "object/:id/zoom/:cmp", :to => 'dams_objects#zoom', :as => 'zoom'
  get "object/:id/:ds", :to => 'file#show', :constraints => { :ds => /[^\/]+/ }, :as => 'file'
  resources :dams_assembled_collections do
    get 'view', :on => :member
  end
  resources :dams_units do
    member do
      get 'view'
      get 'collections'
    end
  end
  resources :dams_copyrights do
  	get 'view', :on => :member
  end
  resources :dams_licenses do
  	get 'view', :on => :member
  end
  resources :dams_other_rights do
  	get 'view', :on => :member
  end
  resources :dams_statutes do
  	get 'view', :on => :member
  end
  resources :dams_languages
  resources :dams_vocabularies
  resources :dams_roles
  resources :dams_provenance_collections
  resources :dams_provenance_collection_parts
  resources :dams_vocabulary_entries
  resources :dams_source_captures
  resources :dams_cartographics
  resources :dams_built_work_places do
    get 'view', :on => :member
  end
  resources :dams_foos do
    get 'view', :on => :member
  end
  resources :dams_foo_bars do
    get 'view', :on => :member
  end
  resources :dams_iconographies do
    get 'view', :on => :member
  end
  resources :dams_style_periods do
    get 'view', :on => :member
  end
  resources :dams_scientific_names do
    get 'view', :on => :member
  end
  resources :dams_techniques do
    get 'view', :on => :member
  end
  resources :dams_cultures do
    get 'view', :on => :member
  end
  resources :dams_cultural_contexts do
    get 'view', :on => :member
  end
  resources :dams_functions do
    get 'view', :on => :member
  end
  resources :mads_personal_names do
    get 'view', :on => :member
  end
  resources :mads_family_names do
    get 'view', :on => :member
  end
  resources :mads_corporate_names do
    get 'view', :on => :member
  end
  resources :mads_conference_names do
    get 'view', :on => :member
  end
  resources :mads_complex_subjects do
    get 'view', :on => :member
  end
  resources :mads_topics do
    get 'view', :on => :member
  end
  resources :mads_temporals do
    get 'view', :on => :member
  end
  resources :mads_names do
    get 'view', :on => :member
  end
  resources :mads_occupations do
    get 'view', :on => :member
  end
  resources :mads_genre_forms do
    get 'view', :on => :member
  end
  resources :mads_geographics do
    get 'view', :on => :member
  end
  resources :mads_schemes do
    get 'view', :on => :member
  end
  resources :mads_authority, :as => 'mads_authorities' do
    get 'view', :on => :member
  end
  resources :mads_languages do
    get 'view', :on => :member
  end

  resources :get_data do
	get 'get_linked_data', :on => :member
	post 'get_linked_data', :on => :member
	get 'get_name', :on => :member
	post 'get_name', :on => :member	
	get 'get_subject', :on => :member
	post 'get_subject', :on => :member
	get 'get_ark', :on => :member		
  end

end

app/models/dams_statute.rb
class DamsStatute < ActiveFedora::Base
  has_metadata 'damsMetadata', :type => DamsStatuteDatastream
  delegate_to "damsMetadata", [:citation,:jurisdiction,:note, :permissionType, :permissionBeginDate, :permissionEndDate, :restrictionType, :restrictionBeginDate, :restrictionEndDate,
  							   :permission_node, :permission_node_attributes, :restriction_node, :restriction_node_attributes ]
end

app/controllers/dams_statutes_controller.rb
class DamsStatutesController < ApplicationController
  include Blacklight::Catalog
  include Dams::ControllerHelper
  load_and_authorize_resource
  skip_load_and_authorize_resource :only => [:index, :show]

  ##############################################################################
  # solr actions ###############################################################
  ##############################################################################
  def show
    parm={ :q => "id_t:#{params[:id]}" }
    @document = get_single_doc_via_search(1,parm)
    @current_statute = @document['name_tesim']
    #@carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel AND id_t:#{params[:id]}", :qt=>"standard")
     @carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel")
  end
  def index

    # solr index
    @response, @document = get_search_results(:q => 'has_model_ssim:"info:fedora/afmodel:DamsStatute"' )
    @carousel_resp, @carousel = get_search_results( :q => "title_tesim:carousel")
  end

  ##############################################################################
  # hydra actions ##############################################################
  ##############################################################################
  def view
    @dams_statute = DamsStatute.find(params[:id])   
  end
  
  def new
    @dams_statute.restriction_node.build
    @dams_statute.permission_node.build
  end

  def edit
  end


  def create
    if @dams_statute.save
        redirect_to @dams_statute, notice: "Statute has been saved"
    else
      flash[:alert] = "Unable to save Statute"
      render :new
    end
  end

  def update
    @dams_statute.restriction_node.clear
    @dams_statute.permission_node.clear  
    @dams_statute.attributes = params[:dams_statute]
    if @dams_statute.save
        redirect_to @dams_statute, notice: "Successfully updated Statute"
    else
      flash[:alert] = "Unable to save Statute"
      render :edit
    end
  end

end

app/helpers/dams_statutes_helper.rb
module DamsStatutesHelper
  def render_statute_list 
    #stub statute list
    render :partial => "dams_statutes/statute_links", :collection => DamsStatute.all, :as => :dams_statute
  end

  def current_statute
    @statute
  end
  private 
end

app/views/dams_statutes/_browse_facet_link.html.erb
<li><%= link_to "<i class='icon-eye-open'></i> #{facet.label}".html_safe, catalog_facet_path(facet.field, :'facet.sort' => 'index'), :class => "btn btn-block  btn-link" %></li>

app/views/dams_statutes/_error_messages.html.erb
<% if @dams_statute.errors.any? %>

	<div class="alert alert-block alert-error">
		<button type="button" class="close" data-dismiss="alert">&times;</button>
		<h4>The form contains <%= pluralize(@dams_statute.errors.count, "error") %></h4>
		<ul>
		<% @dams_statute.errors.full_messages.each do |msg| %>
			<li><%= msg %></li> 
		<% end %>
		</ul>
	</div>

<% end %>

app/views/dams_statutes/_metadata.html.erb
<%
		htmlOpen = "<dt>%s</dt><dd>"
		htmlClose = "</dd>"


		if @document["citation_tesim"] != nil 
		    htmlOpen %= 'Citation'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"citation_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end

		htmlOpen = "<dt>%s</dt><dd>"
		htmlClose = "</dd>"


		if @document["jurisdiction_tesim"] != nil 
		    htmlOpen %= 'Jurisdiction'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"jurisdiction_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end
			
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["permissionType_tesim"] != nil 
		    htmlOpen %= 'Permission Type'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"permissionType_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["permissionBeginDate_tesim"] != nil 
		    htmlOpen %= 'Permission Begin Date'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"permissionBeginDate_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end	
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["permissionEndDate_tesim"] != nil 
		    htmlOpen %= 'Permission End Date'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"permissionEndDate_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end	
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["restrictionType_tesim"] != nil 
		    htmlOpen %= 'Restriction Type'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"restrictionType_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["restrictionBeginDate_tesim"] != nil 
		    htmlOpen %= 'Restriction Begin Date'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"restrictionBeginDate_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end	
		htmlOpen = "<dt>%s</dt><dd>"
		if @document["restrictionEndDate_tesim"] != nil 
		    htmlOpen %= 'Restriction End Date'
		    concat htmlOpen.html_safe
%>		    
			<ul class="unstyled sidebar-button-list">
				<li><%= render_document_show_field_value(:document=>@document, :field=>"restrictionEndDate_tesim").html_safe %></li>
			</ul>
<%
			concat htmlClose.html_safe			
		end		
%>		

app/views/dams_statutes/_search_form.html.erb
<%= form_tag catalog_index_url, :method => :get, :class => 'search-query-form clearfix' do %>
	
	<% unless search_fields.empty? %>
		<label for="dams-search" class="hide-text"><%= t('blacklight.search.form.search_field.label') %></label>
		<%= select_tag(:search_field, options_for_select(search_fields, h(params[:search_field])), :class=>"input-block-level", :id=>"dams-search") %>
		<span class="hide-text"><%= t('blacklight.search.form.search_field.post_label') %></span>
	<% end %>

	<label for="q" class="hide-text"><%= t('blacklight.search.form.q') %></label>
	<%= text_field_tag :q, params[:q], :placeholder => "For keywords...", :class => "search_q q input-block-level", :id => "q"%>

	<button type="submit" class="btn btn-inverse pull-right">
		<i class="icon-search icon-white"></i>
		<span><%=t('blacklight.search.form.submit')%></span>
	</button>

<% end %>

app/views/dams_statutes/_statute_links.html.erb
<li><%= link_to dams_statute.citation.first, dams_statute %></li>

app/views/dams_statutes/edit.html.erb
<h1>Edit DAMS Statute</h1>
<%= form_for @dams_statute do |f| %>
  <%= label_tag 'dams_statute[citation]', "Citation" %><%= text_field_tag 'dams_statute[citation][]', @dams_statute.citation[0] %>
  <%= label_tag 'dams_statute[jurisdiction]', "Jurisdiction" %><%= text_field_tag 'dams_statute[jurisdiction][]', @dams_statute.jurisdiction[0] %>
  <%= label_tag 'dams_statute[note]', "Note" %><%= text_field_tag 'dams_statute[note][]', @dams_statute.note[0] %>
  <%= f.fields_for :permission_node do |pn| %>
    <%= pn.label :type, "Permission Type" %>
    <%= pn.text_field :type , :value => @dams_statute.permissionType[0]%>    
    <%= pn.label :beginDate, "Permission Begin Date" %>
    <%= pn.text_field :beginDate, :value => @dams_statute.permissionBeginDate[0]%>
    <%= pn.label :endDate, "Permission End Date" %>
    <%= pn.text_field :endDate, :value => @dams_statute.permissionEndDate[0]%>    
  <% end %> 

  <%= f.fields_for :restriction_node do |rn| %>
    <%= rn.label :type, "Restriction Type" %>
    <%= rn.text_field :type , :value => @dams_statute.restrictionType[0]%>    
    <%= rn.label :beginDate, "Restriction Begin Date" %>
    <%= rn.text_field :beginDate, :value => @dams_statute.restrictionBeginDate[0]%>
    <%= rn.label :endDate, "Restriction End Date" %>
    <%= rn.text_field :endDate, :value => @dams_statute.restrictionEndDate[0]%>    
  <% end %>    
  <br>
  <%=f.submit "Save", class: "btn btn-primary" %>
  <%= link_to "Cancel", dams_statute_path( @dams_statute ), class: "btn btn-primary" %>
<%end%>

app/views/dams_statutes/index.html.erb
<h1>Statutes</h1>

<div class="span6">
	<ul><%= render_statute_list %></ul>
</div>

<div>
	<% if can? :create, DamsStatute%>
	<%= link_to "Create Statute", new_dams_statute_path, :class => 'btn btn-primary' %>
	<% end %>
</div>
</div>

app/views/dams_statutes/new.html.erb
<h1>Create a new DAMS Statute</h1>
<%= form_for @dams_statute do |f| %>
  <%= label_tag 'dams_statute[citation]', "Citation" %><%= text_field_tag 'dams_statute[citation]' %>
  <%= label_tag 'dams_statute[jurisdiction]', "Jurisdiction" %><%= text_field_tag 'dams_statute[jurisdiction]' %>
  <%= label_tag 'dams_statute[note]', "Note" %><%= text_field_tag 'dams_statute[note]' %>
  <%= f.fields_for :permission_node do |pn| %>
    <%= pn.label :type, "Permission Type" %>
    <%= pn.text_field :type , :value => ""%>    
    <%= pn.label :beginDate, "Permission Begin Date" %>
    <%= pn.text_field :beginDate, :value => ""%>
    <%= pn.label :endDate, "Permission End Date" %>
    <%= pn.text_field :endDate, :value => ""%>    
  <% end %>
  <%= f.fields_for :restriction_node do |rn| %>
    <%= rn.label :type, "Restriction Type" %>
    <%= rn.text_field :type , :value => ""%>    
    <%= rn.label :beginDate, "Restriction Begin Date" %>
    <%= rn.text_field :beginDate, :value => ""%>
    <%= rn.label :endDate, "Restriction End Date" %>
    <%= rn.text_field :endDate, :value => ""%>    
  <% end %>   
  <br>
  <%=f.submit "Save", class: "btn btn-primary" %>
<%end%>

app/views/dams_statutes/show.html.erb
<% @page_title =  "Copyright | #{render_document_show_field_value(:document=>@document, :field=>"status_tesim")} " %>
<% statute = render_document_show_field_value(:document=>@document, :field=>"note_tesim") %>

<div class="row-fluid">

  <div id="content" class="show-document span9">

		<div class="row-fluid">
			<section class="dams-metadata span12">
				<p class="sidebar-header"><strong><%= statute %></strong></p>			
				<dl class="dl-horizontal">
					<%= render :partial => 'metadata' %>
				</dl>	
			</section>
		</div>

	 </div>    
	
	<div class="span3">
	
		<div class="well dams-search-box">
			<h4>Search</h4>
			<%= render_unit_search_bar  %>
		</div>
		
		<p class="sidebar-header"><strong>Browse By</strong></p>
		<ul class="unstyled sidebar-button-list">
			<!-- hack in browse by collection, for RCI demo -->
			<li><%= link_to "<i class='icon-eye-open'></i> Collection".html_safe, dams_collections_path, :class => "btn btn-block  btn-link" %></li>
			<%= render_browse_facet_links %>
		</ul>

    <% if can? :update, @document then %>
			<p class="sidebar-header"><strong>Editor Tools</strong></p>
			<ul class="unstyled sidebar-button-list">
			<li><%= link_to "<i class='icon-plus-sign'></i> Hydra View".html_safe, view_dams_statute_path(@document['id']), class: "btn btn-block btn-small btn-link"%>     
      		<li><%= link_to "<i class='icon-plus-sign'></i> Edit".html_safe, edit_dams_statute_path(@document['id']), class: "btn btn-block btn-small btn-link"%>
			</ul>
    <% end %>
				
	</div>

</div>

app/views/dams_statutes/view.html.erb
<h1><%= @dams_statute.note.first %></h1>
<div>citation: <%= @dams_statute.citation.first %></div>
<div>jurisdiction: <%= @dams_statute.jurisdiction.first %></div>
<div>permissionBeginDate: <%= @dams_statute.permissionBeginDate.first %></div>
<div>permissionEndDate: <%= @dams_statute.permissionEndDate.first %></div>
<div>permissionType: <%= @dams_statute.permissionType.first %></div>
<div>restrictionBeginDate: <%= @dams_statute.restrictionBeginDate.first %></div>
<div>restrictionEndDate: <%= @dams_statute.restrictionEndDate.first %></div>
<div>restrictionType: <%= @dams_statute.restrictionType.first %></div>
<div>
  <% if can? :update, @dams_statute then %>
    <%= link_to "Solr View", dams_statute_path(@dams_statute), class: "btn btn-primary"%>
    <%= link_to "Edit", edit_dams_statute_path(@dams_statute), class: "btn btn-primary" %>
    <%= link_to "View All", dams_statutes_path, class: "btn btn-primary" %>
  <% end %>
  
</div>